# Copyright (C) 2026 Qt Group.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR BSD-3-Clause

AUT=addressbook
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_without_wildcard tst_with_wildcard
VERSION=3
WRAPPERS=Qt
